add Blogody to No-Code Platforms section
automata/awesome-jamstack pull request #81
Opened 2021-08-20 15:35 UTC by styxlab

2021-09-29 16:51 UTC, automata requested changes

2021-09-29 16:51 UTC, automata commented on README.md
> +- [Blogody](https://www.blogody.com) - Create your own blog and see it live in seconds.
Should be placed at end of list of items.

2021-09-29 17:30 UTC, styxlab commented
Also added it to the headless CMS section as Blogody can be used both in "no-code" and "headless" mode.

2022-08-05 04:38 UTC, automata commented
@styxlab please add in only one section and fix the conflict.

2022-08-13 05:13 UTC, automata commented
Closing for now for the lack of updates, @styxlab please feel free to re-open it.

2022-08-13 05:13 UTC, closed without merging